
import java.io.*;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;

/**
 * the frame and the IO
 *
 * @since 2019/1/16
 * @author Jenny Tai
 */
public class UserFrameIO extends javax.swing.JFrame {

    private static ArrayList<User> users;
    private static String fileName;
    private boolean isFromStart;

    /**
     * Constructor, read the file
     * @param isFromStart
     * @param isVsAI
     */
    public UserFrameIO(boolean isFromStart) {
        fileName = "Account Database.txt";
        users = new ArrayList<>();
        this.isFromStart = isFromStart;
        initComponents();
        try {
            read();
        } catch (IOException ex) {
            warn("Failed. I guess it's because you changed the file, did you?");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        javax.swing.JTabbedPane jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        LoginButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loginUser = new javax.swing.JTextField();
        loginPassword = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        signupUser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        signupPassword1 = new javax.swing.JPasswordField();
        SignupButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        signupPassword2 = new javax.swing.JPasswordField();

        jButton1.setText("jButton1");

        setTitle("Log in/Sign up");
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new java.awt.CardLayout());

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Papyrus", 2, 14)); // NOI18N

        jPanel1.setBackground(java.awt.Color.black);

        LoginButton.setFont(new java.awt.Font("Algerian", 2, 30)); // NOI18N
        LoginButton.setForeground(java.awt.Color.green);
        LoginButton.setText("Click Here to Login");
        LoginButton.setToolTipText("");
        LoginButton.setBorderPainted(false);
        LoginButton.setContentAreaFilled(false);
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Papyrus", 2, 24)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Username: ");

        jLabel2.setFont(new java.awt.Font("Papyrus", 2, 24)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Password: ");

        loginUser.setBackground(new java.awt.Color(240, 240, 240));
        loginUser.setFont(new java.awt.Font("Papyrus", 0, 20)); // NOI18N
        loginUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        loginPassword.setBackground(new java.awt.Color(240, 240, 240));
        loginPassword.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        loginPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        loginPassword.setPreferredSize(new java.awt.Dimension(6, 38));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LoginButton)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loginUser, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(loginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(LoginButton)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Log In", jPanel1);

        jPanel2.setBackground(java.awt.Color.black);

        jLabel3.setFont(new java.awt.Font("Papyrus", 2, 24)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Username: ");

        signupUser.setBackground(new java.awt.Color(240, 240, 240));
        signupUser.setFont(new java.awt.Font("Papyrus", 0, 20)); // NOI18N
        signupUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel4.setFont(new java.awt.Font("Papyrus", 2, 24)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Password: ");

        signupPassword1.setBackground(new java.awt.Color(240, 240, 240));
        signupPassword1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        signupPassword1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        signupPassword1.setPreferredSize(new java.awt.Dimension(6, 38));

        SignupButton.setFont(new java.awt.Font("Algerian", 2, 30)); // NOI18N
        SignupButton.setForeground(java.awt.Color.green);
        SignupButton.setText("Click Here to Sign Up");
        SignupButton.setToolTipText("");
        SignupButton.setBorderPainted(false);
        SignupButton.setContentAreaFilled(false);
        SignupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignupButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Papyrus", 2, 24)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Confirm Password: ");

        signupPassword2.setBackground(new java.awt.Color(240, 240, 240));
        signupPassword2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        signupPassword2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        signupPassword2.setPreferredSize(new java.awt.Dimension(6, 38));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(signupUser, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signupPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signupPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SignupButton)
                .addGap(53, 53, 53))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(signupUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(signupPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(signupPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(SignupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        jTabbedPane1.addTab("Sign Up", jPanel2);

        getContentPane().add(jTabbedPane1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        String inputUser = loginUser.getText();
        String inputPassword = new String(loginPassword.getPassword());

        // forct user to input
        if (!"".equals(inputUser)) {
            // get if the username is taken in user array list and get index
            // if it exist, log in
            int i = findName(inputUser);
            if (i < users.size()) {
                if (inputPassword.equals(users.get(i).getPassword())) {
                    SnakeGame.setUser(inputUser, users.get(i).getBest(), i);
                } else {
                    warn("Incorrect password to this username");
                }
            } else {
                warn("This account doesn't exist");
            }
        } else {
            warn("Please enter your user account");
        }
        gameAfterLogin();
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void SignupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignupButtonActionPerformed
        String username = signupUser.getText();
        String password1 = new String(signupPassword1.getPassword());
        String password2 = new String(signupPassword2.getPassword());

        // check for length and space
        if (username.length() < 1 || username.length() > 8 || username.indexOf(' ') > -1) {
            warn("Username must be 1 - 8 characters long");
        } else if (password1.length() < 6 || password1.length() > 16 || password1.indexOf(' ') != -1) {
            warn("Password must be 6 - 16 characters long, without space in between");
            // if name and password are in appropriate style
        } else {
            // check if the username is taken
            // if it isn't and password are safe, sign up to the IO
            if (findName(username) < users.size()) {
                warn("This username already exist");
            } else if (!password1.equals(password2)) {
                warn("Please confirm your password");
            } else {
                users.add(new User(username, password1, 0));
                SnakeGame.setUser(username, 0, users.size() - 1);
                try {
                    print();
                } catch (IOException ex) {
                    warn("Sign up failed");
                }
            }
        }
        gameAfterLogin();
    }//GEN-LAST:event_SignupButtonActionPerformed

    /**
     * update IO by new best score
     *
     * @param rank the index of that user in the array
     * @param newBest the newest best score
     */
    public void newBest(int rank, int newBest) {
        users.get(rank).setBest(newBest);
        // rearrange the array by new score, and update to IO
        Collections.sort(users);
        try {
            print();
        } catch (IOException ex) {
            warn("New Best failed");
        }
    }

    public static int findName(String name) {
        int i;
        for (i = 0; i < users.size(); i++) {
            if (users.get(i).getName().equals(name)) {
                break;
            }
        }
        return i;
    }

    public static User findUser(String name) {
        return users.get(findName(name));
    }

    // easier to output message dialog
    private void warn(String message) {
        JOptionPane.showMessageDialog(null, message, "Error", JOptionPane.ERROR_MESSAGE);
    }

    // copy all arraylist user information to the file
    private void print() throws IOException {
        try (PrintWriter fileOut = new PrintWriter(new BufferedWriter(new FileWriter(fileName)))) {
            Collections.sort(users);
            users.forEach((line) -> {
                fileOut.println(line);
            });
        }
    }

    // read the file and put it into arraylist
    private void read() throws FileNotFoundException, IOException {
        try (BufferedReader fileIn = new BufferedReader(new FileReader(fileName))) {
            String line = fileIn.readLine();
            while (line != null) {
                String name = line.substring(0, line.indexOf(' '));
                String password = line.substring(line.indexOf(' ') + 1, line.lastIndexOf(' '));
                int score = Integer.parseInt(line.substring(line.lastIndexOf(' ') + 1));
                users.add(new User(name, password, score));
                line = fileIn.readLine();
            }
        }
        // cheat
        System.out.println(users);
    }

    private void gameAfterLogin (){
        System.out.println("I'm here");
        if (isFromStart){
            double size = SnakeGame.askSize();
            if (size != 0)
                SnakeGame.startGame(size,false);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginButton;
    private javax.swing.JButton SignupButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField loginPassword;
    private javax.swing.JTextField loginUser;
    private javax.swing.JPasswordField signupPassword1;
    private javax.swing.JPasswordField signupPassword2;
    private javax.swing.JTextField signupUser;
    // End of variables declaration//GEN-END:variables
}
